# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=16)),
                ('puerto', models.IntegerField()),
                ('motor', models.CharField(choices=[('', (('postgres', 'Postgres'),)), ('', (('oracle', 'Oracle'),)), ('', (('mysql', 'Mysql'),))], max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('bd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField(max_length=500)),
                ('descripcion', models.TextField(max_length=300)),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Conexion')),
            ],
        ),
    ]
