# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=50)),
                ('linea_directa', models.CharField(max_length=50)),
            ],
        ),
    ]
