# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_directorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
            ],
        ),
    ]
