# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha',
            field=models.DateField(),
        ),
    ]
