# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-28 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20170928_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='foto',
            field=models.ImageField(upload_to='fotos_articulos'),
        ),
    ]
