# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-05 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20170928_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos_articulo')),
            ],
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
    ]
