# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_estudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
