# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_cargarestudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargarestudiante',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
