# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-01 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_delete_estudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametrizacion',
        ),
        migrations.AlterField(
            model_name='directorio',
            name='extension',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='linea_directa',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
