# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_auto_20171101_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargarEstudiante',
        ),
    ]
