# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_delete_cargarestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargarEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=10)),
                ('programa', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
            ],
        ),
    ]
