# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_cargarestudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargarestudiante',
            old_name='carrera',
            new_name='materia',
        ),
    ]
