# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-03 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_auto_20171102_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargarEstudiante',
        ),
    ]
