# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_delete_cargarestudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametrizacion',
        ),
    ]
