# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_delete_parametrizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametrizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('eslogan', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='fotos_param')),
                ('mision', models.TextField(max_length=500)),
                ('vision', models.TextField(max_length=500)),
                ('informacion', models.CharField(max_length=200)),
                ('estado_directorio', models.CharField(choices=[('', (('activo', 'Activo'),)), ('', (('inactivo', 'Inactivo'),))], max_length=50)),
                ('estado_articulo', models.CharField(choices=[('', (('activo', 'Activo'),)), ('', (('inactivo', 'Inactivo'),))], max_length=50)),
                ('estado_localizacion', models.CharField(choices=[('', (('activo', 'Activo'),)), ('', (('inactivo', 'Inactivo'),))], max_length=50)),
                ('s_hojadevida', models.CharField(choices=[('', (('activo', 'Activo'),)), ('', (('inactivo', 'Inactivo'),))], max_length=50)),
                ('s_ofertaacademica', models.CharField(choices=[('', (('activo', 'Activo'),)), ('', (('inactivo', 'Inactivo'),))], max_length=50)),
                ('s_notasemestre', models.CharField(choices=[('', (('activo', 'Activo'),)), ('', (('inactivo', 'Inactivo'),))], max_length=50)),
                ('s_informacionasignaura', models.CharField(choices=[('', (('activo', 'Activo'),)), ('', (('inactivo', 'Inactivo'),))], max_length=50)),
                ('s_listaestudiantes', models.CharField(choices=[('', (('activo', 'Activo'),)), ('', (('inactivo', 'Inactivo'),))], max_length=50)),
            ],
        ),
    ]
