# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_parametrizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrizacion',
            old_name='s_hojadevida',
            new_name='hoja_de_vida',
        ),
        migrations.RenameField(
            model_name='parametrizacion',
            old_name='s_informacionasignaura',
            new_name='informacion_asignatura',
        ),
        migrations.RenameField(
            model_name='parametrizacion',
            old_name='s_listaestudiantes',
            new_name='lista_estudiantes',
        ),
        migrations.RenameField(
            model_name='parametrizacion',
            old_name='s_notasemestre',
            new_name='nota_semestre',
        ),
        migrations.RenameField(
            model_name='parametrizacion',
            old_name='s_ofertaacademica',
            new_name='oferta_academica',
        ),
    ]
