# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_auto_20171104_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sql',
            name='conexion',
        ),
        migrations.DeleteModel(
            name='Sql',
        ),
    ]
