# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_auto_20171104_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField(max_length=500)),
                ('descripcion', models.TextField(max_length=300)),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Conexion')),
            ],
        ),
    ]
