# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0032_sql'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Localizacion',
        ),
    ]
