# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0035_auto_20171105_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('', (('estudiante', 'Estudiante'),)), ('', (('docente', 'Docente'),)), ('', (('administrativo', 'Administrativo'),))], max_length=50)),
                ('nombre', models.TextField(max_length=50)),
                ('sql', models.TextField(max_length=300)),
                ('descripcion', models.TextField(max_length=300)),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Conexion')),
            ],
        ),
    ]
