# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0037_auto_20171105_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sql',
            name='rol',
            field=models.CharField(choices=[('', (('estudiante', 'Estudiante'),)), ('', (('docente', 'Docente'),)), ('', (('administrativo', 'Administrativo'),)), ('', (('visitante', 'Visitante'),))], max_length=50),
        ),
    ]
