# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0040_auto_20171105_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sql',
            name='rol',
            field=models.CharField(choices=[('', (('estudiante', 'Estudiante'),)), ('', (('docente', 'Docente'),)), ('', (('administrativo', 'Administrativo'),)), ('', (('estudiante y docente', 'Estudiante y Docente'),)), ('', (('docente y administrativo', 'Docente y Administrativo'),)), ('', (('administrativo, docente y estudiante', 'Administrativo, Docente y Estudiante'),)), ('', (('publico', 'Público'),))], max_length=50),
        ),
    ]
