# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-06 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0041_auto_20171105_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sql',
            name='rol',
            field=models.CharField(choices=[('', (('estudiante', 'Estudiante'),)), ('', (('docente', 'Docente'),)), ('', (('administrativo', 'Administrativo'),)), ('', (('estudiante, docente', 'Estudiante, Docente'),)), ('', (('docente, administrativo', 'Docente, Administrativo'),)), ('', (('administrativo, docente ,estudiante', 'Administrativo, Docente, Estudiante'),)), ('', (('publico', 'Público'),))], max_length=50),
        ),
    ]
