# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-06 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0044_auto_20171106_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sql',
            name='rol',
            field=models.CharField(choices=[('', (('administrativo', 'Administrativo'),)), ('', (('docente', 'Docente'),)), ('', (('estudiante', 'Estudiante'),)), ('', (('docente, estudiante', 'Docente, Estudiante'),)), ('', (('administrativo, docente', 'Administrativo, Docente'),)), ('', (('administrativo, docente, estudiante', 'Administrativo, Docente, Estudiante'),)), ('', (('publico', 'Público'),))], max_length=50),
        ),
    ]
