# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0045_auto_20171106_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sql',
            name='sql',
            field=models.TextField(max_length=500),
        ),
    ]
