# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0046_auto_20171205_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexion',
            name='contrasena',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
